'use strict';

const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

// Helpers
const daysAgo = (n) => new Date(Date.now() - n * 86400000);
const daysFromNow = (n) => new Date(Date.now() + n * 86400000);

const JOBS = [
  // ── Middle East ──────────────────────────────────────────────────────────────
  {
    title: 'First Officer – Boeing 777',
    company: 'Emirates',
    location: 'Dubai, UAE',
    country: 'UAE',
    description: 'Emirates is recruiting First Officers for Boeing 777 long-haul operations. Candidates must hold a valid ATPL, Class 1 medical, and a minimum of 2,500 total flight hours. B777 type rating preferred but not required — full conversion training provided. Competitive tax-free salary, accommodation allowance, annual leave tickets, and schooling provided for dependants.',
    applyUrl: 'https://www.emirates.com/english/careers/',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 14000, salaryMax: 18000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA', 'FAA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2500, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(2), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – Airbus A380',
    company: 'Emirates',
    location: 'Dubai, UAE',
    country: 'UAE',
    description: 'Emirates seeks experienced Captains for the Airbus A380 fleet. A minimum of 1,500 hours PIC on multi-engine jet aircraft is required. FAA, EASA or GCAA ATPL holders welcome. Upgrade training to A380 provided. World-class benefit package including tax-free salary, housing, schooling and medical.',
    applyUrl: 'https://www.emirates.com/english/careers/',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 18000, salaryMax: 24000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA', 'FAA'],
    reqAircraftTypes: ['A380'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8000, reqMinPicHours: 1500, reqMinTurbineHours: 5000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(5), expiresAt: daysFromNow(45),
  },
  {
    title: 'First Officer – Airbus A330/A350',
    company: 'Qatar Airways',
    location: 'Doha, Qatar',
    country: 'Qatar',
    description: 'Qatar Airways is expanding its widebody fleet and requires First Officers rated or trainable on the A330/A350 family. Minimum 3,000 total flight hours required, including 1,000 hours on multi-engine jet aircraft. GCAA or EASA ATPL mandatory. Industry-leading package including housing, transport, and 5-star crew hotel stays.',
    applyUrl: 'https://www.qatarairways.com/en/careers.html',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 13000, salaryMax: 17000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['A330', 'A350'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3000, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(1), expiresAt: daysFromNow(90),
  },
  {
    title: 'Captain – Boeing 787 Dreamliner',
    company: 'Qatar Airways',
    location: 'Doha, Qatar',
    country: 'Qatar',
    description: 'Qatar Airways is recruiting Captains for its Boeing 787 Dreamliner fleet. Applicants must hold an ATPL with valid privileges, a minimum of 8,000 total flight hours and 2,000 hours PIC on multi-engine jet. B787 type rating is an advantage. Comprehensive relocation support and tax-free remuneration.',
    applyUrl: 'https://www.qatarairways.com/en/careers.html',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 17000, salaryMax: 22000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['B787'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8000, reqMinPicHours: 2000, reqMinTurbineHours: 6000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(3), expiresAt: daysFromNow(75),
  },
  {
    title: 'First Officer – Boeing 737 MAX',
    company: 'flydubai',
    location: 'Dubai, UAE',
    country: 'UAE',
    description: 'flydubai is growing rapidly and recruiting First Officers for the Boeing 737 MAX fleet. Minimum 2,000 total hours and GCAA or EASA ATPL required. B737 type rating preferred. Attractive tax-free package, productivity pay and annual leave passage.',
    applyUrl: 'https://www.flydubai.com/en/about-flydubai/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 10000, salaryMax: 14000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(7), expiresAt: daysFromNow(50),
  },
  {
    title: 'Captain – Airbus A320 Family',
    company: 'Air Arabia',
    location: 'Sharjah, UAE',
    country: 'UAE',
    description: 'Air Arabia, the Middle East and North Africa\'s first and largest low-cost carrier, is recruiting Captains for its A320 family fleet. GCAA or EASA ATPL, Class 1 medical, and a minimum of 5,000 hours total including 1,500 hours PIC on multi-engine jet required.',
    applyUrl: 'https://www.airarabia.com/en/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 12000, salaryMax: 16000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(10), expiresAt: daysFromNow(40),
  },
  {
    title: 'First Officer – Airbus A320',
    company: 'Etihad Airways',
    location: 'Abu Dhabi, UAE',
    country: 'UAE',
    description: 'Etihad Airways seeks First Officers for its A320 short-haul and medium-haul network. GCAA or EASA ATPL with minimum 2,000 hours total flight time. Tax-free salary, furnished accommodation, education allowance and annual leave passages.',
    applyUrl: 'https://careers.etihad.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 11000, salaryMax: 15000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(4), expiresAt: daysFromNow(55),
  },
  {
    title: 'Captain – Airbus A320 Family',
    company: 'Air Arabia Abu Dhabi',
    location: 'Abu Dhabi, UAE',
    country: 'UAE',
    description: 'Air Arabia Abu Dhabi is a joint venture with Etihad Airways and is rapidly expanding. Captains with GCAA or EASA ATPL, Class 1 medical, A320 type rating and minimum 5,000 hours including 1,500 PIC are invited to apply. Tax-free pay, accommodation and annual leave passages.',
    applyUrl: 'https://www.airarabia.com/en/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 12000, salaryMax: 16000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(4), expiresAt: daysFromNow(55),
  },

  // ── Europe ───────────────────────────────────────────────────────────────────
  {
    title: 'Captain – Airbus A320 Family',
    company: 'Ryanair',
    location: 'Dublin, Ireland',
    country: 'Ireland',
    description: 'Ryanair is Europe\'s largest airline and is growing its A320 fleet. Captains must hold a valid EASA ATPL, Class 1 medical and a minimum of 5,000 total hours including 1,500 hours PIC. Competitive productivity-linked pay, commuter bases across Europe.',
    applyUrl: 'https://careers.ryanair.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 180000, salaryMax: 240000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(30),
  },
  {
    title: 'First Officer – Boeing 737-800',
    company: 'Ryanair',
    location: 'London Stansted, UK',
    country: 'United Kingdom',
    description: 'Ryanair is hiring First Officers across its UK network based at London Stansted. EASA ATPL, Class 1 medical and a minimum of 700 hours total time required. B737 type rating preferred — approved conversion training available. High utilisation, short-haul operation.',
    applyUrl: 'https://careers.ryanair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 65000, salaryMax: 90000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 700, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(8), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Airbus A319/A320/A321',
    company: 'easyJet',
    location: 'London Gatwick, UK',
    country: 'United Kingdom',
    description: 'easyJet is recruiting experienced Captains across its European base network. EASA ATPL with Class 1 medical and 5,000 total hours including 1,000 PIC on jet aircraft required. Progressive remuneration with productivity incentives and flexible rostering.',
    applyUrl: 'https://careers.easyjet.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 140000, salaryMax: 180000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(9), expiresAt: daysFromNow(35),
  },
  {
    title: 'First Officer – Airbus A320neo',
    company: 'Wizz Air',
    location: 'Budapest, Hungary',
    country: 'Hungary',
    description: 'Wizz Air is one of Europe\'s fastest-growing ultra low-cost carriers and is hiring First Officers for the A320neo. EASA ATPL (or licence convertible to EASA), Class 1 medical. Minimum 500 hours total flight time. A320 type rating training offered to eligible candidates.',
    applyUrl: 'https://careers.wizzair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 70000, salaryMax: 110000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 500, reqMinPicHours: 0,
    reqWillingToRelocate: true,
    postedAt: daysAgo(3), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – Airbus A320 Family',
    company: 'Lufthansa',
    location: 'Frankfurt, Germany',
    country: 'Germany',
    description: 'Lufthansa is seeking experienced Captains for its A320 fleet based in Frankfurt and Munich. EASA ATPL, Class 1 medical and 5,500 total hours including 2,000 PIC on multi-engine jet required. Excellent collective-agreement remuneration, defined-benefit pension and staff travel benefits.',
    applyUrl: 'https://careers.lufthansagroup.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 150000, salaryMax: 210000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5500, reqMinPicHours: 2000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(12), expiresAt: daysFromNow(30),
  },
  {
    title: 'First Officer – Airbus A330',
    company: 'Air France',
    location: 'Paris CDG, France',
    country: 'France',
    description: 'Air France is recruiting First Officers for the Airbus A330 on its long-haul network. EASA ATPL mandatory, visite médicale classe 1, minimum 3,000 hours total flight time. Attractive remuneration package including profit-sharing, stake participation and travel benefits.',
    applyUrl: 'https://careers.airfranceklm.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 80000, salaryMax: 120000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A330'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3000, reqMinPicHours: 500, reqMinMultiEngineHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(40),
  },
  {
    title: 'Captain – Boeing 777-200/300ER',
    company: 'KLM Royal Dutch Airlines',
    location: 'Amsterdam, Netherlands',
    country: 'Netherlands',
    description: 'KLM is recruiting Captains for its Boeing 777 long-haul fleet based at Amsterdam Schiphol. EASA ATPL, Class 1 medical. Minimum 8,000 hours total including 2,000 hours PIC on multi-engine jet required. B777 type rating preferred. Strong collective labour agreement with defined-benefit pension.',
    applyUrl: 'https://careers.klm.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 140000, salaryMax: 190000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8000, reqMinPicHours: 2000, reqMinTurbineHours: 5000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(14), expiresAt: daysFromNow(28),
  },
  {
    title: 'First Officer – ATR 72-600',
    company: 'Flybe',
    location: 'Birmingham, UK',
    country: 'United Kingdom',
    description: 'Flybe is rebuilding its regional network and hiring First Officers for ATR 72 operations across UK and Northern Europe. EASA or UK CAA CPL/ATPL, Class 1 medical, multi-engine instrument rating. Minimum 700 hours total. Excellent progressive pay scale and command opportunities.',
    applyUrl: 'https://careers.flybe.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 45000, salaryMax: 65000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['CPL', 'ATPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: ['ATR72'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 700, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(4), expiresAt: daysFromNow(55),
  },
  {
    title: 'A320 Type Rating Instructor (TRI)',
    company: 'CAE',
    location: 'Amsterdam, Netherlands',
    country: 'Netherlands',
    description: 'CAE is expanding its training centre network and hiring A320 Type Rating Instructors for its Amsterdam facility. Applicants must hold an EASA TRI(A) on the A320 family, a minimum of 5,000 hours total including 2,000 PIC on A320/A319/A321. Class 2 medical acceptable. Competitive daily rates.',
    applyUrl: 'https://www.cae.com/careers',
    role: 'INSTRUCTOR',
    contractType: 'CONTRACT',
    region: 'Europe',
    salaryMin: 900, salaryMax: 1400, salaryCurrency: 'EUR', salaryPeriod: 'DAY',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_2',
    reqMinTotalHours: 5000, reqMinPicHours: 2000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(11), expiresAt: daysFromNow(50),
  },
  {
    title: 'First Officer – Embraer E190/E195',
    company: 'SAS Scandinavian Airlines',
    location: 'Stockholm, Sweden',
    country: 'Sweden',
    description: 'SAS is hiring First Officers for the Embraer E190/E195 fleet. EASA ATPL, Class 1 medical, minimum 1,500 total hours. E190 type rating preferred but conversion training available. Attractive package, profit share and generous travel benefits.',
    applyUrl: 'https://www.sasgroup.net/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 600000, salaryMax: 850000, salaryCurrency: 'SEK', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['E190'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: false,
    postedAt: daysAgo(7), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Boeing 737 NG',
    company: 'Norwegian Air Shuttle',
    location: 'Oslo, Norway',
    country: 'Norway',
    description: 'Norwegian is hiring Captains for its Boeing 737 NG fleet based in Oslo and other Scandinavian bases. EASA ATPL, Class 1 medical, minimum 5,000 total hours and 1,000 PIC on B737 required. Competitive package with productivity bonuses and Scandinavian work-life balance.',
    applyUrl: 'https://careers.norwegian.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 900000, salaryMax: 1200000, salaryCurrency: 'NOK', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(9), expiresAt: daysFromNow(35),
  },
  {
    title: 'ATPL Cadet – Sponsored Ab Initio',
    company: 'Lufthansa Aviation Training',
    location: 'Frankfurt, Germany',
    country: 'Germany',
    description: 'Lufthansa offers a fully sponsored ab initio training program. Selected cadets will undergo integrated training at partner flight schools in the US and Europe, leading to an EASA ATPL and type rating on the A320 family. Completion of academic secondary education and a first-class medical certificate required.',
    applyUrl: 'https://lat.lufthansa.com',
    role: 'CADET',
    contractType: 'CADET',
    region: 'Europe',
    salaryMin: null, salaryMax: null, salaryCurrency: null, salaryPeriod: null,
    reqCertificates: [], reqAuthorities: ['EASA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 0, reqMinPicHours: 0,
    reqWillingToRelocate: true,
    postedAt: daysAgo(15), expiresAt: daysFromNow(120),
  },
  {
    title: 'Captain – Airbus A330 Cargo',
    company: 'DHL Air',
    location: 'East Midlands, UK',
    country: 'United Kingdom',
    description: 'DHL Air is hiring Captains for Airbus A330 freighter operations out of East Midlands Airport. EASA ATPL, Class 1 medical. Minimum 6,000 total hours and 1,500 PIC. A330 type rating required. Cargo operations only, night flying involved. Excellent pay and lifestyle roster.',
    applyUrl: 'https://careers.dhl.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 110000, salaryMax: 150000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: ['A330'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 6000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(8), expiresAt: daysFromNow(40),
  },
  {
    title: 'First Officer – Boeing 777 Cargo',
    company: 'Cargolux',
    location: 'Luxembourg City, Luxembourg',
    country: 'Luxembourg',
    description: 'Cargolux, Europe\'s leading all-cargo airline, is hiring First Officers for its Boeing 777F fleet. EASA ATPL, Class 1 medical. Minimum 2,000 hours. B777 type rating preferred. Luxembourg-based with overnight stays worldwide. Excellent LCGB collective agreement.',
    applyUrl: 'https://careers.cargolux.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 90000, salaryMax: 130000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(10), expiresAt: daysFromNow(35),
  },
  {
    title: 'First Officer – Airbus A220-300',
    company: 'Air Baltic',
    location: 'Riga, Latvia',
    country: 'Latvia',
    description: 'airBaltic, Europe\'s number one A220 operator, is hiring First Officers. EASA ATPL, Class 1 medical. Minimum 1,000 total hours. A220 type rating training provided at airBaltic Training Centre. Fast-track carrier with one of Europe\'s youngest fleets.',
    applyUrl: 'https://www.airbaltic.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 60000, salaryMax: 90000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1000, reqMinPicHours: 0,
    reqWillingToRelocate: true,
    postedAt: daysAgo(1), expiresAt: daysFromNow(75),
  },
  {
    title: 'Captain – CRJ-900',
    company: 'SAS Link',
    location: 'Stockholm Arlanda, Sweden',
    country: 'Sweden',
    description: 'SAS Link is recruiting CRJ-900 Captains for its Scandinavian regional network. EASA ATPL, Class 1 medical. CRJ-900 type rating with minimum 5,000 total hours and 1,000 PIC on jet. Competitive Scandinavian pay and working conditions.',
    applyUrl: 'https://www.sasgroup.net/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 750000, salaryMax: 1000000, salaryCurrency: 'SEK', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(40),
  },
  {
    title: 'First Officer – Airbus A320 Family',
    company: 'Turkish Airlines',
    location: 'Istanbul, Turkey',
    country: 'Turkey',
    description: 'Turkish Airlines, one of the world\'s top carriers flying to the most countries, is hiring First Officers for A320 family operations. EASA or FAA ATPL, Class 1 medical. Minimum 1,500 total hours. A320 type rating preferred. Excellent package including accommodation and annual leave passages.',
    applyUrl: 'https://careers.thy.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 8000, salaryMax: 12000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(3), expiresAt: daysFromNow(65),
  },
  {
    title: 'Captain – Boeing 777-300ER',
    company: 'Turkish Airlines',
    location: 'Istanbul, Turkey',
    country: 'Turkey',
    description: 'Turkish Airlines is recruiting Captains for its Boeing 777-300ER widebody fleet. EASA or FAA ATPL, SHGM validation available. Class 1 medical. Minimum 8,000 hours and 2,000 PIC on B777 or similar widebody. Excellent package with housing, schooling and annual leave passages.',
    applyUrl: 'https://careers.thy.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 12000, salaryMax: 18000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8000, reqMinPicHours: 2000, reqMinTurbineHours: 5000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(9), expiresAt: daysFromNow(42),
  },
  {
    title: 'Check Airman – Airbus A320 (TRI)',
    company: 'Wizz Air',
    location: 'Vienna, Austria',
    country: 'Austria',
    description: 'Wizz Air is expanding its training department and recruiting A320 Type Rating Instructors. EASA TRI(A) endorsement on A320 family required. Minimum 5,000 hours including 2,000 PIC on A320. Class 2 medical acceptable. Competitive pay per training day plus benefits.',
    applyUrl: 'https://careers.wizzair.com',
    role: 'INSTRUCTOR',
    contractType: 'CONTRACT',
    region: 'Europe',
    salaryMin: 700, salaryMax: 1000, salaryCurrency: 'EUR', salaryPeriod: 'DAY',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_2',
    reqMinTotalHours: 5000, reqMinPicHours: 2000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(60),
  },
  {
    title: 'First Officer – Airbus A321XLR',
    company: 'Iberia',
    location: 'Madrid, Spain',
    country: 'Spain',
    description: 'Iberia, Spain\'s flag carrier, is the launch operator for the Airbus A321XLR and is hiring First Officers. EASA ATPL, Class 1 medical. Minimum 1,500 hours. A320 family type rating preferred. Excellent work-life balance, strong SEPLA collective agreement.',
    applyUrl: 'https://careers.iberia.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 55000, salaryMax: 90000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: false,
    postedAt: daysAgo(2), expiresAt: daysFromNow(70),
  },
  {
    title: 'Captain – Boeing 737-800',
    company: 'Pegasus Airlines',
    location: 'Istanbul Sabiha Gökçen, Turkey',
    country: 'Turkey',
    description: 'Pegasus Airlines is Turkey\'s leading low-cost carrier and is hiring B737-800 Captains. EASA or FAA ATPL, Class 1 medical. B737 type rating, 5,000 hours and 1,500 PIC required. Competitive package with housing supplement.',
    applyUrl: 'https://careers.flypgs.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 9000, salaryMax: 14000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(8), expiresAt: daysFromNow(42),
  },
  {
    title: 'First Officer – Airbus A319',
    company: 'Aegean Airlines',
    location: 'Athens, Greece',
    country: 'Greece',
    description: 'Aegean Airlines, the only Greek carrier with a 5-star Skytrax rating, is recruiting First Officers for A319 operations. EASA ATPL, Class 1 medical. Minimum 1,200 total hours. A320 family type rating preferred. Lifestyle based in Athens.',
    applyUrl: 'https://careers.aegeanair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 45000, salaryMax: 70000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1200, reqMinPicHours: 150,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(55),
  },
  {
    title: 'Captain – Airbus A350-900',
    company: 'Finnair',
    location: 'Helsinki, Finland',
    country: 'Finland',
    description: 'Finnair, Finland\'s national carrier and pioneer of the transpolar route to Asia, is recruiting Captains for the Airbus A350-900. EASA ATPL, Class 1 medical. Minimum 8,000 hours and 2,000 PIC on widebody jet. A350 type rating training provided. Strong Finnish collective agreement.',
    applyUrl: 'https://careers.finnair.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 110000, salaryMax: 160000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A350'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8000, reqMinPicHours: 2000, reqMinTurbineHours: 5000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(40),
  },
  {
    title: 'First Officer – Embraer E175-E2',
    company: 'Helvetic Airways',
    location: 'Zurich, Switzerland',
    country: 'Switzerland',
    description: 'Helvetic Airways is one of Switzerland\'s independent airlines and is hiring E175-E2 First Officers. EASA ATPL, Class 1 medical. Minimum 700 hours. E-jet type rating training provided at Zurich. Excellent work-life balance with a young, modern fleet.',
    applyUrl: 'https://careers.helvetic.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 75000, salaryMax: 110000, salaryCurrency: 'CHF', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['E190'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 700, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(3), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – Embraer E195-E2',
    company: 'Helvetic Airways',
    location: 'Zurich, Switzerland',
    country: 'Switzerland',
    description: 'Helvetic Airways is one of Switzerland\'s independent airlines and is recruiting Captains for the Embraer E195-E2. EASA ATPL, Class 1 medical. E-jet type rating with minimum 5,000 hours and 1,500 PIC. Based in Zurich with excellent quality of life.',
    applyUrl: 'https://careers.helvetic.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 130000, salaryMax: 170000, salaryCurrency: 'CHF', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['E190'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(8), expiresAt: daysFromNow(45),
  },
  {
    title: 'First Officer – Boeing 737 MAX',
    company: 'Transavia France',
    location: 'Paris Orly, France',
    country: 'France',
    description: 'Transavia France, Air France-KLM\'s low-cost arm, is hiring First Officers for its expanding Boeing 737 MAX fleet. EASA ATPL, Class 1 medical. Minimum 700 hours. B737 type rating training provided. Young, dynamic culture with progressive pay.',
    applyUrl: 'https://careers.transavia.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 55000, salaryMax: 80000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 700, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(1), expiresAt: daysFromNow(80),
  },
  {
    title: 'First Officer – Airbus A320',
    company: 'TAP Air Portugal',
    location: 'Lisbon, Portugal',
    country: 'Portugal',
    description: 'TAP Air Portugal, the Portuguese flag carrier, is hiring First Officers for A320 operations. EASA ATPL, Class 1 medical. Minimum 1,500 total hours. A320 type rating preferred; conversion training available. Strong network to Brazil, Africa and North America.',
    applyUrl: 'https://careers.tapairportugal.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 50000, salaryMax: 75000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: false,
    postedAt: daysAgo(3), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – Challenger 350',
    company: 'NetJets Europe',
    location: 'Lisbon, Portugal',
    country: 'Portugal',
    description: 'NetJets Europe, the world leader in fractional aircraft ownership, is hiring First Officers for the Bombardier Challenger 350. EASA ATPL, Class 1 medical, minimum 1,500 total hours. Challenger 350 type rating training provided. Progressive pay with early Captain upgrade pathway.',
    applyUrl: 'https://careers.netjets.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 55000, salaryMax: 80000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 250,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Gulfstream G650',
    company: 'VistaJet',
    location: 'London, UK',
    country: 'United Kingdom',
    description: 'VistaJet, the leading global private aviation company, is recruiting Captains for the Gulfstream G650. EASA or FAA ATPL, Class 1 medical. G650 type rating with minimum 500 hours on type. International experience and strong service ethos essential. Lifestyle roster with generous off days.',
    applyUrl: 'https://careers.vistajet.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 120000, salaryMax: 170000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 6000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(4), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – ATR 72-500',
    company: 'Air Tahiti',
    location: 'Papeete, French Polynesia',
    country: 'France',
    description: 'Air Tahiti is the domestic carrier serving the islands of French Polynesia and is hiring Captains for the ATR 72-500. EASA ATPL, Class 1 medical. ATR 72 type rating and 3,000 total hours required. Island lifestyle with interisland flying. French language an asset.',
    applyUrl: 'https://www.airtahiti.com/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 80000, salaryMax: 110000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['ATR72'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3000, reqMinPicHours: 500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(13), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Airbus A220-300',
    company: 'Swiss International Air Lines',
    location: 'Zurich, Switzerland',
    country: 'Switzerland',
    description: 'SWISS is the launch operator of the Airbus A220 and is hiring experienced Captains. EASA ATPL, Class 1 medical. A220 or C-Series type rating preferred. Minimum 7,500 hours and 2,000 PIC. Outstanding Swiss quality of life and pay package.',
    applyUrl: 'https://careers.swiss.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 160000, salaryMax: 220000, salaryCurrency: 'CHF', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 7500, reqMinPicHours: 2000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(7), expiresAt: daysFromNow(38),
  },
  {
    title: 'Captain – Boeing 737 Classic',
    company: 'Corendon Airlines',
    location: 'Antalya, Turkey',
    country: 'Turkey',
    description: 'Corendon Airlines is one of Turkey\'s leading leisure carriers and is hiring B737 Classic Captains. EASA ATPL, Class 1 medical. B737 Classic type rating, minimum 5,000 hours and 1,000 PIC. Peak season operation with good availability of rest days off-season.',
    applyUrl: 'https://careers.corendonairlines.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 7000, salaryMax: 11000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(11), expiresAt: daysFromNow(35),
  },
  {
    title: 'First Officer – ATR 42/72',
    company: 'Olympic Air',
    location: 'Athens, Greece',
    country: 'Greece',
    description: 'Olympic Air operates a domestic and island-hopping network in Greece and is recruiting ATR 42/72 First Officers. EASA ATPL or CPL/IR/ME, Class 1 medical. ATR type rating preferred. Minimum 700 hours. Island lifestyle, growing network.',
    applyUrl: 'https://careers.olympicair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 35000, salaryMax: 55000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['CPL', 'ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['ATR72'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 700, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – Saab 340',
    company: 'Loganair',
    location: 'Glasgow, Scotland',
    country: 'United Kingdom',
    description: 'Loganair, the UK\'s largest regional carrier, is recruiting Captains for Saab 340 operations serving the Scottish Highlands and Islands. EASA or UK CAA ATPL, Class 1 medical. Turbo-prop type rating, minimum 3,500 hours including 1,000 PIC. Unique Scottish island-hopping operation.',
    applyUrl: 'https://careers.loganair.co.uk',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 60000, salaryMax: 85000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3500, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(9), expiresAt: daysFromNow(40),
  },

  // ── United States ────────────────────────────────────────────────────────────
  {
    title: 'Captain – Boeing 787 Dreamliner',
    company: 'United Airlines',
    location: 'Houston, TX, USA',
    country: 'United States',
    description: 'United Airlines is adding Boeing 787 Captains across its international network. Applicants must hold a valid FAA ATP certificate with multi-engine privileges, Class 1 medical and a minimum of 6,000 total flight hours including 2,000 PIC. B787 type rating preferred. Industry-leading pay rates per UAL ALPA contract.',
    applyUrl: 'https://careers.united.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 280000, salaryMax: 380000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['B787'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 6000, reqMinPicHours: 2000, reqMinTurbineHours: 4000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(3), expiresAt: daysFromNow(45),
  },
  {
    title: 'First Officer – Boeing 737 MAX',
    company: 'Southwest Airlines',
    location: 'Dallas, TX, USA',
    country: 'United States',
    description: 'Southwest Airlines is hiring First Officers for its Boeing 737 MAX fleet across all US bases. FAA ATP certificate, Class 1 medical required. Minimum 1,500 hours total flight time. B737 type rating training provided. Outstanding SWAPA contract with industry-leading pay, profit sharing and benefits.',
    applyUrl: 'https://careers.southwestair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 80000, salaryMax: 130000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 250,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(40),
  },
  {
    title: 'Captain – Airbus A321neo',
    company: 'American Airlines',
    location: 'Dallas/Fort Worth, TX, USA',
    country: 'United States',
    description: 'American Airlines is hiring Captains for the Airbus A321neo. FAA ATP certificate, Class 1 medical. Minimum 5,000 hours total including 1,000 PIC on multi-engine turbine aircraft. A321 type rating preferred. Top-tier APA pay rates, profit sharing and travel privileges.',
    applyUrl: 'https://jobs.aa.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 240000, salaryMax: 340000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000, reqMinTurbineHours: 3000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(50),
  },
  {
    title: 'First Officer – Boeing 737-900ER',
    company: 'Alaska Airlines',
    location: 'Seattle, WA, USA',
    country: 'United States',
    description: 'Alaska Airlines is hiring First Officers for its Boeing 737 fleet based in Seattle and Los Angeles. FAA ATP or ATP-CTP graduate, Class 1 medical, minimum 1,500 hours. Alaska pilots enjoy industry-leading pay, 401k matching, and one of the best work-life balance records in the industry.',
    applyUrl: 'https://careers.alaskaair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 75000, salaryMax: 120000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 250,
    reqWillingToRelocate: false,
    postedAt: daysAgo(8), expiresAt: daysFromNow(38),
  },
  {
    title: 'Captain – Boeing 767-300ER Cargo',
    company: 'FedEx Express',
    location: 'Memphis, TN, USA',
    country: 'United States',
    description: 'FedEx Express is recruiting Boeing 767 Captains for its international cargo network operating out of Memphis World Hub. FAA ATP, Class 1 medical, minimum 5,000 total hours and 1,500 PIC on multi-engine turbine. B767 experience preferred. Outstanding pension, profit sharing and no passenger service.',
    applyUrl: 'https://careers.fedex.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 260000, salaryMax: 340000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['B767'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500, reqMinTurbineHours: 3500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(10), expiresAt: daysFromNow(42),
  },
  {
    title: 'First Officer – Boeing 737 NG Cargo',
    company: 'UPS Airlines',
    location: 'Louisville, KY, USA',
    country: 'United States',
    description: 'UPS Airlines is hiring First Officers for its Boeing 737 fleet. FAA ATP certificate, Class 1 medical, minimum 1,500 total hours and 200 multi-engine hours required. Night cargo operations. Outstanding ALPA contract with top-tier pay, per-diem, and defined-benefit pension.',
    applyUrl: 'https://careers.ups.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 85000, salaryMax: 140000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 0, reqMinMultiEngineHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(12), expiresAt: daysFromNow(30),
  },
  {
    title: 'First Officer – Embraer E175',
    company: 'SkyWest Airlines',
    location: 'Salt Lake City, UT, USA',
    country: 'United States',
    description: 'SkyWest Airlines, operating as United Express and Delta Connection, is hiring First Officers for the Embraer E175. FAA ATP-CTP graduate, Class 1 medical, minimum 1,500 hours. Fast upgrade track — Captains in under 3 years. Top regional pay with path to major carriers.',
    applyUrl: 'https://careers.skywest.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 70000, salaryMax: 100000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['E190'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(2), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – CRJ-700/900',
    company: 'Envoy Air (American Eagle)',
    location: 'Dallas/Fort Worth, TX, USA',
    country: 'United States',
    description: 'Envoy Air is upgrading First Officers to Captain on the CRJ-700/900. FAA ATP, Class 1 medical. Minimum 1,000 hours in the right seat of a multi-engine turbine aircraft. Fast upgrade guaranteed within 24 months. Excellent pathway to American Airlines mainline.',
    applyUrl: 'https://www.envoyair.com/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 100000, salaryMax: 140000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['CRJ700'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3000, reqMinPicHours: 500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(7), expiresAt: daysFromNow(55),
  },
  {
    title: 'Flight Instructor – Multi-Engine (CFI/CFII/MEI)',
    company: 'CAE USA',
    location: 'Phoenix, AZ, USA',
    country: 'United States',
    description: 'CAE USA is expanding its Phoenix training campus and hiring multi-engine flight instructors holding CFI, CFII and MEI. FAA commercial pilot certificate, minimum 1,000 hours total, 200 hours multi-engine. Build hours fast — 700-800 hours per year. Full benefits and sponsorship toward ATP-CTP.',
    applyUrl: 'https://www.cae.com/careers',
    role: 'INSTRUCTOR',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 55000, salaryMax: 75000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['CPL'], reqAuthorities: ['FAA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1000, reqMinPicHours: 250, reqMinMultiEngineHours: 200,
    reqWillingToRelocate: false,
    postedAt: daysAgo(4), expiresAt: daysFromNow(65),
  },
  {
    title: 'First Officer – Boeing 747-8F Cargo',
    company: 'Atlas Air',
    location: 'New York, NY, USA',
    country: 'United States',
    description: 'Atlas Air is hiring B747-8 Freighter First Officers. FAA ATP, Class 1 medical. Minimum 2,000 total hours. B747 type rating training provided for suitably qualified pilots. Cargo operations worldwide. Competitive ALPA pay rates, 401k and healthcare.',
    applyUrl: 'https://careers.atlasair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 100000, salaryMax: 145000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: [], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(7), expiresAt: daysFromNow(50),
  },
  {
    title: 'B737 TRI/TRE – Contract',
    company: 'FlightSafety International',
    location: 'Dallas, TX, USA',
    country: 'United States',
    description: 'FlightSafety International is hiring contract B737 Type Rating Instructors and Examiners for its Dallas learning centre. FAA TRI(A) and/or DPE designation on the B737 series, minimum 5,000 hours total and 2,000 PIC on B737. Flexible roster, daily rate plus expenses. Class 2 medical acceptable.',
    applyUrl: 'https://www.flightsafety.com/careers',
    role: 'INSTRUCTOR',
    contractType: 'CONTRACT',
    region: 'North America',
    salaryMin: 800, salaryMax: 1200, salaryCurrency: 'USD', salaryPeriod: 'DAY',
    reqCertificates: ['ATPL'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_2',
    reqMinTotalHours: 5000, reqMinPicHours: 2000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(2), expiresAt: daysFromNow(90),
  },
  {
    title: 'Captain – Bombardier Dash 8 Q400',
    company: 'Horizon Air (Alaska Regional)',
    location: 'Seattle, WA, USA',
    country: 'United States',
    description: 'Horizon Air is upgrading to Captain on the Bombardier Q400. FAA ATP, Class 1 medical. Minimum 2,500 total and 1,000 turboprop PIC hours. Q400 type rating preferred. Pathway to Alaska Airlines mainline with seniority protections.',
    applyUrl: 'https://careers.horizonair.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 130000, salaryMax: 175000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['Q400'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2500, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(3), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – ATR 72 Regional',
    company: 'Silver Airways',
    location: 'Fort Lauderdale, FL, USA',
    country: 'United States',
    description: 'Silver Airways is hiring First Officers for ATR 72 operations serving the Bahamas and Caribbean. FAA ATP, Class 1 medical, minimum 1,500 hours. ATR 72 type rating training provided. Island-based lifestyle, competitive pay and rapid upgrade to Captain.',
    applyUrl: 'https://jobs.silverairways.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 65000, salaryMax: 85000, salaryCurrency: 'USD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATP'], reqAuthorities: ['FAA'],
    reqAircraftTypes: ['ATR72'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 250,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(65),
  },

  // ── Canada ───────────────────────────────────────────────────────────────────
  {
    title: 'First Officer – Boeing 737 MAX',
    company: 'Air Canada',
    location: 'Toronto, Canada',
    country: 'Canada',
    description: 'Air Canada is hiring First Officers for the Boeing 737 MAX. Transport Canada (TCCA) ATPL with multi-engine IFR, Class 1 medical. Minimum 2,000 total flight hours. B737 type rating advantageous. Strong ALPA (ACPA) collective agreement with competitive pay scales, defined-benefit pension and full travel privileges.',
    applyUrl: 'https://www.aircanada.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 110000, salaryMax: 160000, salaryCurrency: 'CAD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['TCCA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 250,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(45),
  },
  {
    title: 'First Officer – Embraer E190',
    company: 'Jazz Aviation (Air Canada Express)',
    location: 'Vancouver, Canada',
    country: 'Canada',
    description: 'Jazz Aviation, operating as Air Canada Express, is growing its E190 fleet and recruiting First Officers. TCCA ATPL or CPL with ATPL written complete, Class 1 medical, minimum 1,000 hours. E190 type rating training provided. Fast upgrade track within Jazz and pathway to Air Canada mainline.',
    applyUrl: 'https://www.jazzaviation.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 75000, salaryMax: 110000, salaryCurrency: 'CAD', salaryPeriod: 'YEAR',
    reqCertificates: ['CPL', 'ATPL'], reqAuthorities: ['TCCA'],
    reqAircraftTypes: ['E190'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1000, reqMinPicHours: 250,
    reqWillingToRelocate: false,
    postedAt: daysAgo(9), expiresAt: daysFromNow(50),
  },
  {
    title: 'Captain – Boeing 737-800',
    company: 'Sunwing Airlines',
    location: 'Toronto, Canada',
    country: 'Canada',
    description: 'Sunwing Airlines is a leading Canadian leisure carrier and is hiring B737-800 Captains for seasonal and year-round operations to sun destinations. TCCA ATPL, Class 1 medical. B737 type rating with 5,000 hours and 1,500 PIC. Lifestyle roster with extended vacation.',
    applyUrl: 'https://careers.sunwingtravel.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'North America',
    salaryMin: 160000, salaryMax: 210000, salaryCurrency: 'CAD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['TCCA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(11), expiresAt: daysFromNow(35),
  },

  // ── Asia Pacific ─────────────────────────────────────────────────────────────
  {
    title: 'Captain – Boeing 777',
    company: 'Singapore Airlines',
    location: 'Singapore',
    country: 'Singapore',
    description: 'Singapore Airlines seeks experienced B777 Captains to join its award-winning long-haul operations. ATPL (any major authority), Class 1 medical, minimum 8,000 total hours and 2,000 PIC on multi-engine jet. B777 type rating preferred. World-class package including housing allowance, schooling and annual leave passages.',
    applyUrl: 'https://careers.singaporeair.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 18000, salaryMax: 26000, salaryCurrency: 'SGD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8000, reqMinPicHours: 2000, reqMinTurbineHours: 5000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(6), expiresAt: daysFromNow(30),
  },
  {
    title: 'First Officer – Airbus A350',
    company: 'Singapore Airlines',
    location: 'Singapore',
    country: 'Singapore',
    description: 'Singapore Airlines is recruiting First Officers for its Airbus A350 fleet. ATPL (EASA, CAAS or FAA), Class 1 medical, minimum 3,000 total hours. A350 type rating preferred; full conversion training provided for suitably experienced candidates. Based in Singapore with accommodation support.',
    applyUrl: 'https://careers.singaporeair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 12000, salaryMax: 18000, salaryCurrency: 'SGD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['A350'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3000, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(3), expiresAt: daysFromNow(60),
  },
  {
    title: 'Captain – Boeing 777/787',
    company: 'Cathay Pacific',
    location: 'Hong Kong',
    country: 'Hong Kong',
    description: 'Cathay Pacific is recruiting Captains for its Boeing 777 and 787 fleet. ATPL (any major authority), Class 1 medical. Minimum 8,500 total flight hours including 2,000 PIC on widebody jet. CAAC validation provided. Competitive tax-advantaged package with housing and schooling allowances.',
    applyUrl: 'https://www.cathaypacific.com/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 150000, salaryMax: 210000, salaryCurrency: 'HKD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B777', 'B787'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8500, reqMinPicHours: 2000, reqMinTurbineHours: 6000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(8), expiresAt: daysFromNow(35),
  },
  {
    title: 'First Officer – Airbus A320/A321',
    company: 'AirAsia',
    location: 'Kuala Lumpur, Malaysia',
    country: 'Malaysia',
    description: 'AirAsia is expanding its fleet rapidly and recruiting First Officers for A320/A321 operations. EASA, FAA or CAAC ATPL, Class 1 medical. Minimum 1,500 total hours. A320 type rating preferred. Competitive package with allowances and fast-track upgrade opportunities.',
    applyUrl: 'https://careers.airasia.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 12000, salaryMax: 18000, salaryCurrency: 'MYR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'FAA', 'CAAC'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 250,
    reqWillingToRelocate: true,
    postedAt: daysAgo(4), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – Airbus A380',
    company: 'Qantas Airways',
    location: 'Sydney, Australia',
    country: 'Australia',
    description: 'Qantas is recruiting First Officers for its iconic Airbus A380 fleet. EASA, FAA or CASA ATPL, Class 1 medical. Minimum 3,000 hours including 1,000 on multi-engine jet. A380 type rating training provided to suitably experienced candidates. Based in Sydney.',
    applyUrl: 'https://careers.qantas.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 160000, salaryMax: 220000, salaryCurrency: 'AUD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['CASA', 'EASA', 'FAA'],
    reqAircraftTypes: ['A380'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 3000, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(11), expiresAt: daysFromNow(40),
  },
  {
    title: 'Captain – Boeing 737 MAX',
    company: 'Virgin Australia',
    location: 'Brisbane, Australia',
    country: 'Australia',
    description: 'Virgin Australia is hiring Captains for its Boeing 737 MAX fleet. CASA or EASA ATPL, Class 1 medical. Minimum 5,000 hours and 1,500 PIC on multi-engine turbine jet. B737 type rating required. Excellent package including profit share, staff travel and competitive pay.',
    applyUrl: 'https://careers.virginaustralia.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 140000, salaryMax: 200000, salaryCurrency: 'AUD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['CASA', 'EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(3), expiresAt: daysFromNow(50),
  },
  {
    title: 'First Officer – Airbus A320neo',
    company: 'IndiGo',
    location: 'New Delhi, India',
    country: 'India',
    description: 'IndiGo, India\'s largest carrier by passenger volume, is aggressively growing its A320neo fleet and recruiting First Officers. DGCA CPL/ATPL, Class 1 medical, minimum 200 hours. A320 type rating training provided. Excellent career growth in a dynamic operation.',
    applyUrl: 'https://careers.goindigo.in',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 180000, salaryMax: 300000, salaryCurrency: 'INR', salaryPeriod: 'MONTH',
    reqCertificates: ['CPL', 'ATPL'], reqAuthorities: ['DGCA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 200, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(2), expiresAt: daysFromNow(90),
  },
  {
    title: 'Captain – Airbus A320 Family',
    company: 'IndiGo',
    location: 'Mumbai, India',
    country: 'India',
    description: 'IndiGo is India\'s biggest airline and is always looking for experienced Captains for A320 family operations. DGCA ATPL, Class 1 medical. A320 type rating and minimum 5,000 total hours and 1,500 PIC required. Very strong growth story with excellent command and upgrade opportunities.',
    applyUrl: 'https://careers.goindigo.in',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 700000, salaryMax: 1000000, salaryCurrency: 'INR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['DGCA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – Airbus A330-300',
    company: 'Korean Air',
    location: 'Seoul, South Korea',
    country: 'South Korea',
    description: 'Korean Air is expanding its A330 fleet and recruiting international First Officers. FAA or EASA ATPL (JCAB validation available), Class 1 medical. Minimum 2,500 total hours including 1,000 on multi-engine jet. Attractive expat package including housing allowance.',
    applyUrl: 'https://recruit.koreanair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 7000, salaryMax: 10000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['JCAB', 'EASA', 'FAA'],
    reqAircraftTypes: ['A330'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2500, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(5), expiresAt: daysFromNow(50),
  },
  {
    title: 'Captain – Boeing 777-200LR',
    company: 'Air New Zealand',
    location: 'Auckland, New Zealand',
    country: 'New Zealand',
    description: 'Air New Zealand is hiring Captains for its ultra-long-haul Boeing 777-200LR operating non-stop to New York and London. CASA, EASA or FAA ATPL (CAANZ validation provided). Class 1 medical. Minimum 8,500 hours and 2,000 PIC on widebody jet required. B777 type rating highly preferred.',
    applyUrl: 'https://careers.airnewzealand.co.nz',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 200000, salaryMax: 280000, salaryCurrency: 'NZD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['CASA', 'EASA', 'FAA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 8500, reqMinPicHours: 2000, reqMinTurbineHours: 6000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(7), expiresAt: daysFromNow(35),
  },
  {
    title: 'First Officer – Boeing 787-9',
    company: 'Air New Zealand',
    location: 'Auckland, New Zealand',
    country: 'New Zealand',
    description: 'Air New Zealand is growing its Dreamliner fleet and recruiting First Officers for B787-9 operations. CAANZ, CASA, EASA or FAA ATPL, Class 1 medical. Minimum 2,500 total hours. B787 type rating training provided. Based in Auckland.',
    applyUrl: 'https://careers.airnewzealand.co.nz',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 120000, salaryMax: 170000, salaryCurrency: 'NZD', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['CASA', 'EASA', 'FAA'],
    reqAircraftTypes: ['B787'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2500, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(4), expiresAt: daysFromNow(50),
  },
  {
    title: 'First Officer – Boeing 787-10',
    company: 'Scoot (Singapore Airlines Group)',
    location: 'Singapore',
    country: 'Singapore',
    description: 'Scoot, Singapore Airlines Group\'s long-haul low-cost carrier, is hiring First Officers for its Boeing 787-10 fleet. EASA, FAA or CAAS ATPL, Class 1 medical. Minimum 1,500 total hours. B787 type rating training provided. Part of the world\'s most awarded airline group.',
    applyUrl: 'https://careers.flyscoot.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 8000, salaryMax: 13000, salaryCurrency: 'SGD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B787'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(2), expiresAt: daysFromNow(75),
  },
  {
    title: 'First Officer – Airbus A330-300',
    company: 'Malaysia Airlines',
    location: 'Kuala Lumpur, Malaysia',
    country: 'Malaysia',
    description: 'Malaysia Airlines is modernising its fleet and seeking First Officers for A330-300 long-haul operations. EASA, FAA or Malaysian DCA ATPL, Class 1 medical. Minimum 2,500 total hours. A330 type rating preferred. Full conversion training available for qualified candidates.',
    applyUrl: 'https://careers.malaysiaairlines.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 14000, salaryMax: 20000, salaryCurrency: 'MYR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['A330'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2500, reqMinPicHours: 500, reqMinMultiEngineHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(10), expiresAt: daysFromNow(45),
  },
  {
    title: 'First Officer – Boeing 737 MAX 8',
    company: 'Lion Air',
    location: 'Jakarta, Indonesia',
    country: 'Indonesia',
    description: 'Lion Air, Southeast Asia\'s largest low-cost carrier, is aggressively expanding and hiring international First Officers for its 737 MAX fleet. FAA or EASA ATPL, Class 1 medical, minimum 1,500 hours. B737 type rating training provided. Tax-free pay, accommodation allowance.',
    applyUrl: 'https://careers.lionair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 6000, salaryMax: 9000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(4), expiresAt: daysFromNow(60),
  },
  {
    title: 'First Officer – Boeing 737-800',
    company: 'Air India Express',
    location: 'Kochi, India',
    country: 'India',
    description: 'Air India Express is expanding on short-haul routes to the Gulf and is hiring First Officers for the Boeing 737-800. DGCA ATPL, Class 1 medical, minimum 1,500 hours. B737 type rating preferred. Competitive package with good work-life balance.',
    applyUrl: 'https://careers.airindia.in',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 200000, salaryMax: 350000, salaryCurrency: 'INR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['DGCA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(50),
  },

  // ── Africa ───────────────────────────────────────────────────────────────────
  {
    title: 'Captain – Boeing 737-800',
    company: 'Ethiopian Airlines',
    location: 'Addis Ababa, Ethiopia',
    country: 'Ethiopia',
    description: 'Ethiopian Airlines, Africa\'s largest carrier, is hiring Captains for Boeing 737-800 operations. EASA, FAA or ECAA ATPL, Class 1 medical, minimum 5,000 total and 1,000 PIC. B737 type rating required. Competitive expat package including housing, transport and annual leave passages.',
    applyUrl: 'https://www.ethiopianairlines.com/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Africa',
    salaryMin: 8000, salaryMax: 12000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(8), expiresAt: daysFromNow(60),
  },
  {
    title: 'First Officer – Airbus A350',
    company: 'Ethiopian Airlines',
    location: 'Addis Ababa, Ethiopia',
    country: 'Ethiopia',
    description: 'Ethiopian Airlines is expanding its A350 long-haul network and requires experienced First Officers. EASA or FAA ATPL, Class 1 medical, minimum 2,500 hours. A350 type rating preferred. Full conversion training provided. Housing, transport and leave passages included.',
    applyUrl: 'https://www.ethiopianairlines.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Africa',
    salaryMin: 5500, salaryMax: 8000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['A350'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2500, reqMinPicHours: 500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(10), expiresAt: daysFromNow(55),
  },
  {
    title: 'Captain – Boeing 737 Classic',
    company: 'RwandAir',
    location: 'Kigali, Rwanda',
    country: 'Rwanda',
    description: 'RwandAir is growing rapidly and requires Captains for Boeing 737 operations. EASA or FAA ATPL, Class 1 medical, minimum 4,500 hours and 1,000 PIC. B737 type rating required. Competitive expat package including accommodation, transport and annual leave.',
    applyUrl: 'https://www.rwandair.com/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Africa',
    salaryMin: 7000, salaryMax: 10000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 4500, reqMinPicHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(6), expiresAt: daysFromNow(45),
  },
  {
    title: 'First Officer – Airbus A320',
    company: 'EgyptAir',
    location: 'Cairo, Egypt',
    country: 'Egypt',
    description: 'EgyptAir is hiring First Officers for its Airbus A320 medium-haul fleet. EASA or ECAA ATPL, Class 1 medical. Minimum 1,500 total flight hours. A320 type rating training provided for suitable candidates. Competitive package including housing allowance and annual leave passages.',
    applyUrl: 'https://www.egyptair.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Africa',
    salaryMin: 3500, salaryMax: 5500, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(14), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Boeing 737-800',
    company: 'Kenya Airways',
    location: 'Nairobi, Kenya',
    country: 'Kenya',
    description: 'Kenya Airways is recruiting Captains for Boeing 737-800 operations across Africa and regional routes. EASA or FAA ATPL, Class 1 medical. B737 type rating required, minimum 5,000 hours and 1,000 PIC. Competitive package with Nairobi-based lifestyle benefits.',
    applyUrl: 'https://careers.kenya-airways.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Africa',
    salaryMin: 7500, salaryMax: 11000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(9), expiresAt: daysFromNow(40),
  },
  {
    title: 'Captain – Airbus A321',
    company: 'Air Arabia Maroc',
    location: 'Casablanca, Morocco',
    country: 'Morocco',
    description: 'Air Arabia Maroc is expanding its North African network and recruiting A321 Captains. EASA ATPL, Class 1 medical. A320 family type rating required, minimum 5,000 total hours and 1,500 PIC. French and/or Arabic language skills advantageous. Competitive package.',
    applyUrl: 'https://www.airarabia.com/en/careers',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Africa',
    salaryMin: 10000, salaryMax: 14000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(12), expiresAt: daysFromNow(38),
  },

  // ── South America ────────────────────────────────────────────────────────────
  {
    title: 'Captain – Airbus A320',
    company: 'LATAM Airlines',
    location: 'São Paulo, Brazil',
    country: 'Brazil',
    description: 'LATAM Airlines is the largest airline group in Latin America and is hiring A320 Captains for domestic and regional operations. ANAC (Brazilian) ATPL or licence convertible to ANAC. Class 1 medical, minimum 5,000 hours and 1,500 PIC on jet aircraft. A320 type rating required.',
    applyUrl: 'https://careers.latam.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'South America',
    salaryMin: 30000, salaryMax: 45000, salaryCurrency: 'BRL', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['ANAC'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(50),
  },
  {
    title: 'First Officer – Boeing 737 MAX',
    company: 'Gol Linhas Aéreas',
    location: 'São Paulo, Brazil',
    country: 'Brazil',
    description: 'Gol, Brazil\'s leading low-cost carrier, is hiring First Officers for its all-Boeing 737 MAX fleet. ANAC ATPL or ATPL trainee with frozen ATPL, Class 1 medical, minimum 800 hours. B737 type rating training provided. Excellent career path in a young, dynamic operation.',
    applyUrl: 'https://careers.voegol.com.br',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'South America',
    salaryMin: 15000, salaryMax: 22000, salaryCurrency: 'BRL', salaryPeriod: 'MONTH',
    reqCertificates: ['CPL', 'ATPL'], reqAuthorities: ['ANAC'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 800, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(7), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – Boeing 737 MAX 10',
    company: 'Copa Airlines',
    location: 'Panama City, Panama',
    country: 'Panama',
    description: 'Copa Airlines, rated Latin America\'s most on-time airline, is hiring First Officers for its Boeing 737 MAX fleet at Tocumen International Airport, the Hub of the Americas. FAA or EASA ATPL, Class 1 medical. Minimum 1,500 hours. B737 type rating training available.',
    applyUrl: 'https://careers.copaair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'South America',
    salaryMin: 4500, salaryMax: 7000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['FAA', 'EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 250,
    reqWillingToRelocate: true,
    postedAt: daysAgo(6), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – Airbus A320neo',
    company: 'Vistara (Air India)',
    location: 'Delhi, India',
    country: 'India',
    description: 'Vistara, a full-service carrier and subsidiary of Air India/Tata Sons, is recruiting First Officers for A320neo operations. DGCA ATPL, Class 1 medical. Minimum 1,000 hours total. A320 type rating a strong advantage. Strong career path within the expanding Tata aviation group.',
    applyUrl: 'https://www.airvistara.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 200000, salaryMax: 350000, salaryCurrency: 'INR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['DGCA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1000, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(2), expiresAt: daysFromNow(70),
  },

  // ── Additional roles to reach 100 ────────────────────────────────────────────
  {
    title: 'Captain – Airbus A320neo',
    company: 'Vueling Airlines',
    location: 'Barcelona, Spain',
    country: 'Spain',
    description: 'Vueling, IAG\'s Barcelona-based low-cost carrier, is hiring A320neo Captains. EASA ATPL, Class 1 medical. A320 family type rating, 5,000 hours total and 1,500 PIC required. Progressive productivity pay with bases across Spain and Southern Europe.',
    applyUrl: 'https://careers.vueling.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 80000, salaryMax: 120000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(4), expiresAt: daysFromNow(50),
  },
  {
    title: 'First Officer – Boeing 737 MAX',
    company: 'Jet2.com',
    location: 'Leeds Bradford, UK',
    country: 'United Kingdom',
    description: 'Jet2.com, the UK\'s fastest-growing leisure airline, is hiring First Officers for its B737 MAX fleet. EASA or UK CAA ATPL, Class 1 medical. Minimum 500 hours. B737 type rating training provided. Industry-leading pay, guaranteed base, and a genuinely crew-focused culture.',
    applyUrl: 'https://careers.jet2.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 60000, salaryMax: 85000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 500, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(2), expiresAt: daysFromNow(75),
  },
  {
    title: 'Captain – Airbus A320 Family',
    company: 'TUI Airways',
    location: 'London Luton, UK',
    country: 'United Kingdom',
    description: 'TUI Airways is the UK\'s largest charter airline and is hiring A320 family Captains. EASA or UK CAA ATPL, Class 1 medical. A320 type rating, 5,000 total and 1,500 PIC. Lifestyle roster with significant days off between rotations. Staff holiday discounts.',
    applyUrl: 'https://careers.tui.co.uk',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 100000, salaryMax: 145000, salaryCurrency: 'GBP', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'CAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(7), expiresAt: daysFromNow(40),
  },
  {
    title: 'First Officer – Airbus A330',
    company: 'Condor Airlines',
    location: 'Frankfurt, Germany',
    country: 'Germany',
    description: 'Condor, Germany\'s popular leisure carrier, is recruiting First Officers for its Airbus A330 long-haul fleet. EASA ATPL, Class 1 medical. Minimum 2,000 hours. A330 type rating preferred — full conversion training provided. Holiday destinations worldwide.',
    applyUrl: 'https://careers.condor.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 65000, salaryMax: 100000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A330'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 400,
    reqWillingToRelocate: false,
    postedAt: daysAgo(5), expiresAt: daysFromNow(55),
  },
  {
    title: 'Captain – Boeing 777F',
    company: 'Qatar Airways Cargo',
    location: 'Doha, Qatar',
    country: 'Qatar',
    description: 'Qatar Airways Cargo, the world\'s leading air cargo carrier, is recruiting B777F Captains. GCAA or EASA ATPL, Class 1 medical. B777 type rating, minimum 6,000 total hours and 1,500 PIC. Pure cargo operation with excellent tax-free remuneration and allowances.',
    applyUrl: 'https://www.qatarairways.com/en/careers.html',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 16000, salaryMax: 22000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['B777'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 6000, reqMinPicHours: 1500, reqMinTurbineHours: 4000,
    reqWillingToRelocate: true,
    postedAt: daysAgo(3), expiresAt: daysFromNow(60),
  },
  {
    title: 'First Officer – Airbus A320',
    company: 'Fly Baghdad',
    location: 'Baghdad, Iraq',
    country: 'Iraq',
    description: 'Fly Baghdad is Iraq\'s premier private airline and is expanding its A320 operations. EASA or FAA ATPL, Class 1 medical. Minimum 1,500 hours. A320 type rating preferred. Tax-free expat package including accommodation, transport, 30 days leave per month worked and annual repatriation.',
    applyUrl: 'https://www.flybaghdad.net/careers',
    role: 'FIRST_OFFICER',
    contractType: 'CONTRACT',
    region: 'Middle East',
    salaryMin: 8000, salaryMax: 12000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(9), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Boeing 737-800',
    company: 'SpiceJet',
    location: 'Gurugram, India',
    country: 'India',
    description: 'SpiceJet, one of India\'s leading low-cost carriers, is recruiting B737-800 Captains. DGCA ATPL, Class 1 medical. B737 type rating with 5,000 total hours and 1,000 PIC. Competitive package with good lifestyle opportunities.',
    applyUrl: 'https://careers.spicejet.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 500000, salaryMax: 750000, salaryCurrency: 'INR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['DGCA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(6), expiresAt: daysFromNow(45),
  },
  {
    title: 'Captain – Airbus A320',
    company: 'Batik Air (Lion Group)',
    location: 'Kuala Lumpur, Malaysia',
    country: 'Malaysia',
    description: 'Batik Air Malaysia, the full-service arm of the Lion Group, is hiring A320 Captains for domestic and regional ASEAN operations. FAA or EASA ATPL, Class 1 medical. A320 type rating, 5,000 hours and 1,500 PIC. Competitive package and expat accommodation.',
    applyUrl: 'https://careers.batikairmalaysia.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 22000, salaryMax: 32000, salaryCurrency: 'MYR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA', 'FAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(8), expiresAt: daysFromNow(42),
  },
  {
    title: 'First Officer – Airbus A319',
    company: 'Air Astana',
    location: 'Almaty, Kazakhstan',
    country: 'Kazakhstan',
    description: 'Air Astana, Central Asia\'s premier airline and a Skytrax 4-star carrier, is hiring First Officers for A319/A320 operations. EASA ATPL, Class 1 medical. Minimum 1,500 total hours. A320 type rating preferred. Competitive expat package with accommodation and annual leave.',
    applyUrl: 'https://www.airastana.com/careers',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 5000, salaryMax: 8000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(11), expiresAt: daysFromNow(50),
  },
  {
    title: 'Captain – Boeing 767-300',
    company: 'LOT Polish Airlines',
    location: 'Warsaw, Poland',
    country: 'Poland',
    description: 'LOT Polish Airlines is one of the world\'s oldest carriers and is hiring Boeing 767 Captains for transatlantic and medium-haul operations. EASA ATPL, Class 1 medical. B767 type rating, 7,000 total hours and 2,000 PIC required. Excellent EASA-regulated remuneration.',
    applyUrl: 'https://careers.lot.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 90000, salaryMax: 130000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B767'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 7000, reqMinPicHours: 2000, reqMinTurbineHours: 4500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(10), expiresAt: daysFromNow(38),
  },
  {
    title: 'First Officer – Boeing 737-800',
    company: 'WizzAir Abu Dhabi',
    location: 'Abu Dhabi, UAE',
    country: 'UAE',
    description: 'Wizz Air Abu Dhabi, the ultra-low-cost joint venture with ADQ, is hiring First Officers for B737-800 operations. EASA or GCAA ATPL, Class 1 medical. Minimum 700 hours. B737 type rating training provided. Tax-free salary, accommodation support and annual leave.',
    applyUrl: 'https://careers.wizzair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 9000, salaryMax: 13000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['GCAA', 'EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 700, reqMinPicHours: 0,
    reqWillingToRelocate: true,
    postedAt: daysAgo(3), expiresAt: daysFromNow(65),
  },
  {
    title: 'Captain – Boeing 737 MAX',
    company: 'Neos Air',
    location: 'Milan Malpensa, Italy',
    country: 'Italy',
    description: 'Neos Air, Italy\'s independent leisure carrier, is recruiting B737 MAX Captains for holiday routes across Europe, Africa and the Americas. EASA ATPL, Class 1 medical. B737 type rating, 5,000 hours and 1,000 PIC. Italian language advantageous.',
    applyUrl: 'https://careers.neosair.it',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 80000, salaryMax: 120000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['B737'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1000,
    reqWillingToRelocate: false,
    postedAt: daysAgo(12), expiresAt: daysFromNow(36),
  },
  {
    title: 'First Officer – Airbus A320',
    company: 'Air Malta',
    location: 'Malta',
    country: 'Malta',
    description: 'Air Malta, the Maltese flag carrier operating under its rebranding initiative, is hiring First Officers for A320 operations. EASA ATPL, Class 1 medical. Minimum 1,000 hours. A320 type rating preferred; conversion training available. Mediterranean island lifestyle based in Valletta.',
    applyUrl: 'https://careers.airmalta.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Europe',
    salaryMin: 45000, salaryMax: 65000, salaryCurrency: 'EUR', salaryPeriod: 'YEAR',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['EASA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1000, reqMinPicHours: 0,
    reqWillingToRelocate: false,
    postedAt: daysAgo(1), expiresAt: daysFromNow(80),
  },
  {
    title: 'Captain – Airbus A330-200',
    company: 'Gulf Air',
    location: 'Manama, Bahrain',
    country: 'Bahrain',
    description: 'Gulf Air, the Kingdom of Bahrain\'s national carrier, is recruiting Captains for the Airbus A330-200. GCAA, EASA or FAA ATPL, Class 1 medical. A330 type rating, 7,000 total hours and 1,500 PIC. Tax-free remuneration with accommodation, transport and schooling.',
    applyUrl: 'https://careers.gulfair.com',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 14000, salaryMax: 20000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA', 'FAA'],
    reqAircraftTypes: ['A330'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 7000, reqMinPicHours: 1500, reqMinTurbineHours: 4500,
    reqWillingToRelocate: true,
    postedAt: daysAgo(5), expiresAt: daysFromNow(55),
  },
  {
    title: 'First Officer – Boeing 787-9',
    company: 'Oman Air',
    location: 'Muscat, Oman',
    country: 'Oman',
    description: 'Oman Air, Oman\'s national carrier, is hiring First Officers for its Boeing 787-9 fleet. GCAA, EASA or FAA ATPL, Class 1 medical. Minimum 2,000 hours. B787 type rating training provided for experienced candidates. Tax-free package with accommodation, transport and annual repatriation.',
    applyUrl: 'https://careers.omanair.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 10000, salaryMax: 14000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['GCAA', 'EASA', 'FAA'],
    reqAircraftTypes: ['B787'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 2000, reqMinPicHours: 400,
    reqWillingToRelocate: true,
    postedAt: daysAgo(7), expiresAt: daysFromNow(50),
  },
  {
    title: 'Captain – Airbus A320 Family',
    company: 'IndiGo',
    location: 'Hyderabad, India',
    country: 'India',
    description: 'IndiGo is opening a new hub at Hyderabad Rajiv Gandhi International Airport and requires Captains to be based there. DGCA ATPL, Class 1 medical. A320 type rating with 5,000 hours and 1,500 PIC. Strong performance incentives and progression to widebody fleets.',
    applyUrl: 'https://careers.goindigo.in',
    role: 'CAPTAIN',
    contractType: 'PERMANENT',
    region: 'Asia Pacific',
    salaryMin: 650000, salaryMax: 950000, salaryCurrency: 'INR', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL'], reqAuthorities: ['DGCA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 5000, reqMinPicHours: 1500,
    reqWillingToRelocate: false,
    postedAt: daysAgo(4), expiresAt: daysFromNow(60),
  },
  {
    title: 'First Officer – Airbus A320',
    company: 'Saudia (Saudi Arabian Airlines)',
    location: 'Jeddah, Saudi Arabia',
    country: 'Saudi Arabia',
    description: 'Saudia, Saudi Arabia\'s national carrier, is recruiting First Officers for A320 operations. GCAA, EASA or FAA ATPL, Class 1 medical. Minimum 1,500 total hours. A320 type rating preferred. Tax-free package with accommodation, transport, schooling allowance and 30 days annual leave.',
    applyUrl: 'https://careers.saudia.com',
    role: 'FIRST_OFFICER',
    contractType: 'PERMANENT',
    region: 'Middle East',
    salaryMin: 10000, salaryMax: 14000, salaryCurrency: 'USD', salaryPeriod: 'MONTH',
    reqCertificates: ['ATPL', 'CPL'], reqAuthorities: ['GCAA', 'EASA', 'FAA'],
    reqAircraftTypes: ['A320'], reqMedicalClass: 'CLASS_1',
    reqMinTotalHours: 1500, reqMinPicHours: 200,
    reqWillingToRelocate: true,
    postedAt: daysAgo(6), expiresAt: daysFromNow(55),
  },
];

async function main() {
  // Demo pilot
  const passwordHash = await bcrypt.hash('password123', 12);
  const pilot = await prisma.pilot.upsert({
    where: { email: 'demo@cockpithire.dev' },
    update: {},
    create: {
      email: 'demo@cockpithire.dev',
      passwordHash,
      firstName: 'Demo',
      lastName: 'Pilot',
      country: 'United States',
      city: 'New York',
      willingToRelocate: true,
      certificates: {
        create: {
          type: 'ATP',
          issuingAuthority: 'FAA',
          certificateNumber: 'ATP-123456',
          issueDate: new Date('2020-01-01'),
        },
      },
      medicals: {
        create: {
          medicalClass: 'CLASS_1',
          issuingAuthority: 'FAA',
          issueDate: new Date('2023-06-01'),
          expiryDate: new Date('2025-06-01'),
        },
      },
    },
  });
  console.log(`Seeded pilot: ${pilot.email}`);

  // Clear existing seeded jobs (keep any real scraped jobs with sourcePlatform set)
  await prisma.job.deleteMany({ where: { sourcePlatform: null } });

  const created = await prisma.job.createMany({ data: JOBS });
  console.log(`Seeded ${created.count} jobs`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
