const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  // Demo pilot
  const passwordHash = await bcrypt.hash('password123', 12);
  const pilot = await prisma.pilot.upsert({
    where: { email: 'demo@cockpithire.dev' },
    update: {},
    create: {
      email: 'demo@cockpithire.dev',
      passwordHash,
      firstName: 'Demo',
      lastName: 'Pilot',
      country: 'United States',
      city: 'New York',
      willingToRelocate: true,
      certificates: {
        create: {
          type: 'ATP',
          issuingAuthority: 'FAA',
          certificateNumber: 'ATP-123456',
          issueDate: new Date('2020-01-01'),
        },
      },
      medicals: {
        create: {
          medicalClass: 'CLASS_1',
          issuingAuthority: 'FAA',
          issueDate: new Date('2023-06-01'),
          expiryDate: new Date('2025-06-01'),
        },
      },
    },
  });
  console.log(`Seeded pilot: ${pilot.email}`);

  // Sample jobs
  const jobs = [
    {
      title: 'First Officer – Boeing 737 MAX',
      company: 'Emirates',
      location: 'Dubai, UAE',
      country: 'UAE',
      description: 'Emirates is seeking First Officers rated on the Boeing 737 MAX. You will operate flights across our expanding Middle East and Asia network.',
      applyUrl: 'https://www.emirates.com/careers',
      reqCertificates: ['ATP'],
      reqAuthorities: ['GCAA', 'EASA', 'FAA'],
      reqAircraftTypes: ['B737'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 2500,
      reqMinPicHours: 500,
      reqWillingToRelocate: true,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Captain – Airbus A320 Family',
      company: 'Ryanair',
      location: 'Dublin, Ireland',
      country: 'Ireland',
      description: 'Join Ryanair as a Captain on our A320 fleet. Competitive package including base salary, productivity pay and travel benefits.',
      applyUrl: 'https://www.ryanair.com/careers',
      reqCertificates: ['ATP', 'CPL'],
      reqAuthorities: ['EASA'],
      reqAircraftTypes: ['A320'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 5000,
      reqMinPicHours: 1500,
      reqWillingToRelocate: false,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'First Officer – Airbus A330/A350',
      company: 'Qatar Airways',
      location: 'Doha, Qatar',
      country: 'Qatar',
      description: 'Qatar Airways is expanding its widebody fleet and seeks experienced First Officers for A330 and A350 operations.',
      applyUrl: 'https://www.qatarairways.com/careers',
      reqCertificates: ['ATP'],
      reqAuthorities: ['GCAA', 'EASA'],
      reqAircraftTypes: ['A330', 'A350'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 3000,
      reqMinPicHours: 500,
      reqMinMultiEngineHours: 1000,
      reqWillingToRelocate: true,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Captain – Boeing 777 Long Haul',
      company: 'Singapore Airlines',
      location: 'Singapore',
      country: 'Singapore',
      description: 'Singapore Airlines seeks experienced B777 Captains to join our long-haul operations. World-class benefits and career development.',
      applyUrl: 'https://www.singaporeair.com/careers',
      reqCertificates: ['ATP'],
      reqAuthorities: ['CASA', 'EASA', 'FAA'],
      reqAircraftTypes: ['B777'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 8000,
      reqMinPicHours: 3000,
      reqMinTurbineHours: 5000,
      reqWillingToRelocate: true,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'First Officer – ATR 72 Regional',
      company: 'Flybe',
      location: 'Birmingham, UK',
      country: 'United Kingdom',
      description: 'Flybe is rebuilding its regional network and hiring First Officers for ATR 72 operations across UK and Europe.',
      applyUrl: 'https://www.flybe.com/careers',
      reqCertificates: ['CPL', 'ATP'],
      reqAuthorities: ['CAA_UK', 'EASA'],
      reqAircraftTypes: ['ATR72'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 700,
      reqMinPicHours: 0,
      reqWillingToRelocate: false,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'ATPL Cadet – Ab Initio Program',
      company: 'Lufthansa Aviation Training',
      location: 'Frankfurt, Germany',
      country: 'Germany',
      description: 'Lufthansa offers a fully sponsored ab initio training program leading to a type rating on the A320 family and a contract with Eurowings.',
      applyUrl: 'https://lat.lufthansa.com',
      reqCertificates: ['PPL'],
      reqAuthorities: ['EASA'],
      reqAircraftTypes: [],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 0,
      reqWillingToRelocate: true,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Captain – Boeing 787 Dreamliner',
      company: 'United Airlines',
      location: 'Houston, TX, USA',
      country: 'United States',
      description: 'United Airlines is adding B787 Captains at its Houston hub. Strong pay rates, comprehensive benefits and a clear upgrade path.',
      applyUrl: 'https://www.united.com/careers',
      reqCertificates: ['ATP'],
      reqAuthorities: ['FAA'],
      reqAircraftTypes: ['B787'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 6000,
      reqMinPicHours: 2000,
      reqMinTurbineHours: 4000,
      reqWillingToRelocate: false,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'First Officer – Embraer E190',
      company: 'Air Canada Express',
      location: 'Toronto, Canada',
      country: 'Canada',
      description: 'Air Canada Express is growing and needs E190 First Officers. Fast-track upgrade opportunities for high performers.',
      applyUrl: 'https://www.aircanada.com/careers',
      reqCertificates: ['CPL', 'ATP'],
      reqAuthorities: ['TCCA'],
      reqAircraftTypes: ['E190'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 1000,
      reqMinPicHours: 250,
      reqWillingToRelocate: false,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Simulator Instructor – A320 (TRI/TRE)',
      company: 'CAE',
      location: 'Amsterdam, Netherlands',
      country: 'Netherlands',
      description: 'CAE is hiring Type Rating Instructors and Examiners for the Airbus A320 family. Flexible scheduling and competitive daily rates.',
      applyUrl: 'https://www.cae.com/careers',
      reqCertificates: ['ATP'],
      reqAuthorities: ['EASA'],
      reqAircraftTypes: ['A320'],
      reqMedicalClass: 'CLASS_2',
      reqMinTotalHours: 5000,
      reqMinPicHours: 2000,
      reqWillingToRelocate: false,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'First Officer – Boeing 737 NG Cargo',
      company: 'FedEx Express',
      location: 'Memphis, TN, USA',
      country: 'United States',
      description: 'FedEx Express is expanding its overnight cargo network and recruiting B737 First Officers. No passenger service, night operations.',
      applyUrl: 'https://www.fedex.com/careers',
      reqCertificates: ['ATP'],
      reqAuthorities: ['FAA'],
      reqAircraftTypes: ['B737'],
      reqMedicalClass: 'CLASS_1',
      reqMinTotalHours: 2000,
      reqMinPicHours: 500,
      reqMinInstrumentHours: 75,
      reqWillingToRelocate: true,
      status: 'ACTIVE',
      postedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
    },
  ];

  await prisma.job.deleteMany({});
  await prisma.job.createMany({ data: jobs });
  console.log(`Seeded ${jobs.length} jobs`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
